<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\AuthService\src\AuthService.Contracts\AuthService.Contracts.csproj" />
      <ProjectReference Include="..\ClanService.Contracts\ClanService.Contracts.csproj" />
      <ProjectReference Include="..\ClanService.Domain\ClanService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="owlip.shared.core" />
      <PackageReference Include="owlip.shared.framework" />
    </ItemGroup>

</Project>
