services:
  auth-migrator:
    container_name: auth-migrator
    build:
      context: ./backend
      dockerfile: AuthService/Dockerfile
      target: migrations
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
      secrets:
        - nuget_password
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__AuthDb=${ConnectionStrings__AuthDb}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["--connection", "${ConnectionStrings__AuthDb}"]
    restart: "no"

  auth-service:
    container_name: auth-service
    build:
      context: ./backend
      dockerfile: AuthService/Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
      secrets:
        - nuget_password
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__AuthDb=${ConnectionStrings__AuthDb}
    depends_on:
      postgres:
        condition: service_healthy
      auth-migrator:
        condition: service_completed_successfully
    restart: always

  postgres:
    container_name: auth-db-postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  nuget_password:
    environment: NUGET_PASSWORD

volumes:
  auth-postgres-data:
