<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>
        <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\AuthService\src\AuthService.Contracts\AuthService.Contracts.csproj" />
      <ProjectReference Include="..\ClanService.Core\ClanService.Core.csproj" />
      <ProjectReference Include="..\ClanService.Domain\ClanService.Domain.csproj" />
      <ProjectReference Include="..\ClanService.Infrastructure.Postgres\ClanService.Infrastructure.Postgres.csproj" />
    </ItemGroup>

</Project>
