<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuthService.Contracts\AuthService.Contracts.csproj" />
      <ProjectReference Include="..\AuthService.Domain\AuthService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="owlip.shared.core" />
      <PackageReference Include="owlip.shared.framework" />
      <PackageReference Include="owlip.shared.messaging" />
    </ItemGroup>

</Project>
